config/routes.rb
GetHomeSafeNyc::Application.routes.draw do
  resources :locations
  post "/search" => "locations#search"
  get "/terms" => "welcome#terms"
  get "/press" => "welcome#press"
  root :to => 'locations#index'
end

app/models/borough.rb
class Borough < ActiveRecord::Base
  attr_accessible :name
end

app/models/feature.rb
class Feature < ActiveRecord::Base
  attr_accessible :name
  has_and_belongs_to_many :locations
end

app/models/feature_location.rb
class FeatureLocation < ActiveRecord::Base
  attr_accessible :feature_id, :location_id
end

app/models/feature_status.rb
class FeatureStatus < ActiveRecord::Base
  attr_accessible :feature_id, :status_id
end

app/models/location.rb
class Location < ActiveRecord::Base
  self.per_page = 20

  attr_accessible :address, :borough_id, :latitude, :longitude, :verified, :borough, :safe, :power, :elevators_safe, :elevators_available, :heat, :water, :flooding, :elevator_status

  attr_accessor :newly_created

  belongs_to :borough

  validates_presence_of :address, :uniqueness => true

  class NoAddress < RuntimeError
  end

  def self.for_address address
    cached_location = find_by_address(address) or raise NoAddress
    #address = cached_location.address
    cached_location
    #address.nil? ? Location::NoAddress : address
  end

  def self.save_address(address)
    #address = nil if address == Location::NoAddress
    create(:address => address)
  end

end

app/models/location_feature.rb
class LocationFeature < ActiveRecord::Base
  attr_accessible :feature_id, :location_id
end

app/models/status.rb
class Status < ActiveRecord::Base
  attr_accessible :safe
  has_and_belongs_to_many :features
end

app/models/zip.rb
class Zip < ActiveRecord::Base
  attr_accessible :zipcode
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/locations_controller.rb
class LocationsController < ApplicationController
  def index
    @locations = Location.order('created_at DESC').page(params[:page])
  end

  def new
    #borough = Borough.where(:name => params[:borough]).first
    #Borough.find_by_
    @location = Location.new
  end

  def edit
    @location = Location.find(params[:id])
  end

  def search
    address = params[:address]
    @locations = Location.where("address like ?", "%#{address}%").page(params[:page])
    if @locations.size > 1
      render 'index' and return
    elsif @locations.size == 1
      redirect_to @locations.first and return
    else
      #@locations = Location.all
      flash.now[:error] = "Unable to find location."
      render 'index'
    end
  end

  def show
    @location = Location.find(params[:id])
  end

  def create
    location = Location.new(params[:location])
    @location = LocationCache.for_address location.address.chomp if location.address.present?
    if @location.address.blank?
      flash.now[:error] = "Unable to find location."
      render :action => 'new' and return
    elsif new_record && @location.update_attributes(params[:location].except(:address))
      redirect_to @location and return 
    elsif !new_record
      flash[:notice] = "Location already exists."
      redirect_to @location
    else
      render :action => 'new'
    end
  end

  def update
    @location = Location.find(params[:id])
    if @location.update_attributes(params[:location].except(:address))
      redirect_to @location
    else
      flash.now[:error] = "Unable to update location info."
      render action: "edit"
    end
  end
  private
  def new_record
    @location.present? and @location.created_at > 1.minutes.ago 
  end

end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end

  def new
    @location = Location.new
  end

  def create
  end

  def terms
  end

  def press
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/locations_helper.rb
module LocationsHelper
  def is_safe location
    location.safe ? "safe" : "notsafe"
  end
  
  def safe_label location
    location.safe ? "Safe" : "Not Safe"
  end

  def elevator_present
    @location.elevator_status == "Yes" or @location.elevator_status == "No"
  end

  def elevator_safe
    @location.elevator_status == "Yes" 
  end
  
  def address_local location
    s = location.address
    s.slice! ", USA"
    s
  end
    
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
<title>Get Home Safe NYC</title>
<%= stylesheet_link_tag    "application", :media => "all" %>
<%= javascript_include_tag "application" %>
<%= csrf_meta_tags %>
<meta http-equiv="content-type" content="text/html; charset=utf-8" />
<link rel="Shortcut Icon" href="/favicon.ico" type="image/x-icon" />
<meta name="robots" content="all" />
<meta property="og:image" content="http://gethomesafenyc.com/images/ghs.png"/>

<meta name="description" content="Get Home Safe NYC is available for residents of New York City to update and discover the status of critical resources at their homes and apartments in the wake of Hurricane Sandy.">
  <meta name="author" content="Illuminati Creative">

  <!-- http://t.co/dKP3o1e -->
  <meta name="HandheldFriendly" content="True">
  <meta name="MobileOptimized" content="320">
  <meta http-equiv="CACHE-CONTROL" content="NO-CACHE">

  <!--[if (lt IE 9) & (!IEMobile)]>
  <script src="js/libs/selectivizr-min.js"></script>
  <![endif]-->


  <!-- For iPhone 4 -->
  <link rel="apple-touch-icon-precomposed" sizes="114x114" href="img/h/apple-touch-icon.png">
  <!-- For iPad 1-->
  <link rel="apple-touch-icon-precomposed" sizes="72x72" href="img/m/apple-touch-icon.png">
  <!-- For iPhone 3G, iPod Touch and Android -->
  <link rel="apple-touch-icon-precomposed" href="img/l/apple-touch-icon-precomposed.png">
  <!-- For Nokia -->
  <link rel="shortcut icon" href="img/l/apple-touch-icon.png">
  <!-- For everything else -->
  <link rel="shortcut icon" href="/favicon.ico">

  <!--iOS. Delete if not required -->
  <meta name="apple-mobile-web-app-capable" content="yes">
  <meta name="apple-mobile-web-app-status-bar-style" content="black-translucent">
  <link rel="apple-touch-startup-image" href="img/splash.png">

  <meta name="viewport" content="width=device-width, target-densitydpi=160dpi, initial-scale=1.0, user-scalable=0, minimum-scale=1.0, maximum-scale=1.0">
  <meta name="apple-mobile-web-app-capable" content="yes" />

  <!--Microsoft. Delete if not required -->
  <meta http-equiv="cleartype" content="on">
  <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">
  <!--[if lt IE 7 ]><script src="//ajax.googleapis.com/ajax/libs/chrome-frame/1.0.2/CFInstall.min.js"></script><script>window.attachEvent("onload",function(){CFInstall.check({mode:"overlay"})})</script><![endif]-->


<script type="text/javascript">

var _gaq = _gaq || [];
  _gaq.push(['_setAccount', 'UA-21919807-2']);
  _gaq.push(['_trackPageview']);

  (function() {
    var ga = document.createElement('script'); ga.type = 'text/javascript'; ga.async = true;
    ga.src = ('https:' == document.location.protocol ? 'https://ssl' : 'http://www') + '.google-analytics.com/ga.js';
    var s = document.getElementsByTagName('script')[0]; s.parentNode.insertBefore(ga, s);
  })();

</script>	
</head>
<body>
	<div class="container clearfix">
	<%= render "shared/header" %>
		<div class="content clearfix">
			<div id="flash">
		  	<% if flash[:notice] %>
			    <p class="notice"><%= flash[:notice] %></p>
			<% end %>
			<% if flash[:error] %>
			    <p class="error"><%= flash[:error] %></p>
			<% end %>
		</div>
		<%= yield %>
	</div>
	<%= render "shared/right_info" %>
	<%= render "shared/footer" %>
	</div>
</body>
</html>

app/views/locations/_flash.html.erb
<div id="container">
  <% if flash[:notice] %>
    <p class="notice"><%= flash[:notice] %></p>
<% end %>
  <% if flash[:error] %>
    <p class="error"><%= flash[:error] %></p>
<% end %> c
</div>

app/views/locations/_form.html.erb
<div class="location clearfix">
  <% if @location.address %>
  <p class="address"><%= @location.address %>
  </p><% end %>
  <%= form_for(@location) do |f| %>
  <% if !@location.address %>
  <fieldset class="address">  
    <label for="address">Address</label>
    <%= f.text_field :address %>
  </fieldset>
  <% end %>
  <fieldset>  
    <label for="safe">Residence is safe?</label>
    <%= f.check_box :safe %>
  </fieldset>
  <fieldset>  
    <label for="power">Residence has power?</label>
    <%= f.check_box :power %>
  </fieldset>
  <fieldset>  
    <label for="heat">Residence has heat?</label>
    <%= f.check_box :heat %>
  </fieldset>
  <fieldset>  
    <label for="water">Residence has water?</label>
    <%= f.check_box :water %>
  </fieldset>
  <fieldset>  
    <label for="flooding">Residence is flooded?</label>
    <%= f.check_box :flooding %>
  </fieldset>
  <fieldset class="elevator">
  	<label for="elivator_status">Elevators are working?</label>
	<div class="radios">
      <%= f.radio_button(:elevator_status, "Yes") %>
	    <label class="radio">Yes</label>
      <%= f.radio_button(:elevator_status, "No") %>
	    <label class="radio">No</label>
      <%= f.radio_button(:elevator_status, "N/A") %>
	    <label class="radio">N/A</label>
	</div>
  </fieldset>
  <fieldset>
  <input type="hidden" name="location[elevators_available]" value="0">
  <input type="hidden" name="location[elevators_safe]" value="0">
  
  <% if @location.address %>
  <%= f.submit 'Submit', :onclick => "return confirm('Are you sure you want to update this address?')" %>
  <% else %>
  <%= f.submit 'Submit', :onclick => "return confirm('Are you sure you want to add this address?')" %>
  <% end %>
  <a href="/"><input name="cancel" type="button" value="Cancel"></a>
  </fieldset>

<% end %>
</div>

app/views/locations/edit.html.erb
<h2>Update Building Status</h2>
<%= render "form" %>

app/views/locations/index.html.erb
<% if @locations.present? %>
<table id="locations">	
  <thead>
    <tr>
      <th class="safety">Status</th>			
      <th class="address">Address</th>
      <th class="updated">Last Updated</th>
    </tr>
  </thead>
</table>
<table>
  <tbody>
    <% @locations.each do |location| %>
    <tr class="<%= cycle("odd", "even") %>">
    <td class="safety <%=is_safe(location)%>"><img src="images/<%=is_safe(location)%>.svg"/></td>			
    <td class="address"><%= link_to address_local(location), location %></td>
    <td class="updated"><%= location.updated_at.strftime("%m/%d/%Y %I:%M%p") %></td>
  	</tr>
	<% end %>
</tbody>
</table>
<%= will_paginate @locations, :class=>'clearfix pagination', :next_label=> '>', :previous_label=> '<', :inner_window=> 1 %>
<% else %>
<% end %>

app/views/locations/new.html.erb
<h2>Add Building Status</h2>
<%= render :partial => "form", :locals => { :display_address => true } %>    

app/views/locations/show.html.erb
<section class="single">
	<div class="address clearfix">
		<div class="status <%=is_safe(@location)%> clearfix">
			<h2 class="status"><%=safe_label(@location)%></h2>
			<h4>Last Updated</h4>
			<h3 class="update"><%= @location.updated_at.strftime("%m/%d/%Y %I:%M%p") %></h3>
		</div>
		<p><%= address_local(@location) %></p>
	</div>
	<ul class="statuses clearfix">
		<li><img src="/images/<%= @location.power ? "safe" : "notsafe"%>.svg"/><p>Power</p></li>
		<li><img src="/images/<%= @location.water ? "safe" : "notsafe"%>.svg"/><p>Water</p></li>
		<li><img src="/images/<%= @location.heat ? "safe" : "notsafe"%>.svg"/><p>Heat</p></li>
		<% if @location.flooding %><li><img src="/images/notsafe.svg"/><p>Flooding</p></li><% end %>
    <% if elevator_present %>
      <li><img src="/images/<%= elevator_safe ? "safe" : "notsafe"%>.svg"/><p>Elevators</p></li>
    <% end %>
	</ul>
	<div class="map">
		<div class="map-holder">
	    <iframe width="100%" height="100%" frameborder="0" scrolling="no" marginheight="0" marginwidth="0" src="https://maps.google.com/maps?q=<%= @location.address %>&amp;ie=UTF8&amp;hq=&amp;hnear=<%= @location.address %>&amp;gl=us&amp;t=m&amp;z=15&amp;output=embed&amp;iwloc=near"></iframe>
		</div>
	</div>
	<div class="status-footer clearfix">
	  <ul class="utility">
	    <li><%= link_to "Update Status »", edit_location_path(@location) %></li>
	  </ul>
	</div>
  <!--<ul class="social">
    <li><a href="#">Facebook</a></li>
    <li><a href="#">Twitter</a></li>						
  </ul>-->
</section>

app/views/locations/update.html.erb
<h1>Locations#update</h1>
<p>Find me in app/views/locations/update.html.erb</p>

app/views/shared/_footer.html.erb
<footer class="clearfix">
	<ul class="social clearfix">
		<li><iframe src="//www.facebook.com/plugins/like.php?href=http%3A%2F%2Fgethomesafenyc.com&amp;send=false&amp;layout=button_count&amp;width=74&amp;show_faces=false&amp;action=like&amp;colorscheme=light&amp;font=arial&amp;height=21&amp;appId=135962049879310" scrolling="no" frameborder="0" style="border:none; overflow:hidden; width:74px; height:21px;" allowTransparency="true"></iframe></li>
		<li><a href="https://twitter.com/share" class="twitter-share-button" data-url="http://gethomesafenyc.com" data-text="Help your fellow New Yorkers!" data-hashtags="gethomesafenyc">Tweet</a>
		<script>!function(d,s,id){var js,fjs=d.getElementsByTagName(s)[0];if(!d.getElementById(id)){js=d.createElement(s);js.id=id;js.src="//platform.twitter.com/widgets.js";fjs.parentNode.insertBefore(js,fjs);}}(document,"script","twitter-wjs");</script></li>
	</ul>
	<ul class="footer-nav clearfix">
		<li><a href="/terms">Terms &amp; Conditions</a></li>
		<li><a href="/press">Press</a></li>
		<li>Website by <a href="http://www.illcreative.com" target="_blank">illuminati</a></li>
	</ul>
</footer>

app/views/shared/_header.html.erb
<header class="clearfix">
	<h1 class="title"><a href="/">Get Home Safe NYC</a></h1>
	<%= link_to "Add your Address!", new_location_path,  :class=>'update_link' %>
	<image class="fbimg" src="/images/ghs.png"/>
	<div class="navigation clearfix">
		<div class="search">
      		<%= form_tag('/search', :class =>'form-search') %>
        		<input type="text" name="address" id="address" autofocus class="input-medium search-query" placeholder="Search...">
			  	<button type="submit" class="btn">Search</button>
			</form>
		</div>
	</div>
</header>

app/views/shared/_left_info.html.erb
<div class="sidebar">
	<section>
		<h2>About</h2>
		<p>Get Home Safe NYC is available for residents of New York City to update and discover the status of critical resources at their homes and apartments in the wake of Hurricane Sandy. The website allows landlords and fellow residents to list their address and mark whether the residence has power, electricity, running water, working elevators (if applicable) or has experienced flooding. Most importantly, it will indicate if it is safe to return to the residence.</p>
		<p><span class="prompt">Do you know your building's status?</span> <br/><a href="#">Update your neighbors here »</a></p>
		<p><span class="prompt">Disclaimer: The following information is for public informational purposes only and is not reviewed by the site owners. Get Home Safe NYC and its parents assume no responsibility to parties receiving and using the information. By using this website you acknowledge this.</span></p>
	</section>
	<section>
		<h3>Resources:</h3>
		<ul class="resources">
			<li><a href="http://www.nyc.gov" target="_blank">NYC.gov</a></li>
			<li><a href="https://twitter.com/notifynyc" target="_blank">Notify NYC</a></li>
			<li><a href="http://project.wnyc.org/transit-tracker/embed.html" target="_blank">Transit Tracker</a></li>
			<li><a href="http://google.org/crisismap/2012-sandy" target="_blank">Google Crisis Map</a></li>
			<li><a href="http://coned.com" target="_blank">Con Edison</a></li>
			<li><a href="http://www.disasterassistance.gov/" target="_blank">Disaster Assistance</a></li>
		</ul>
	</section>
	<div class="illcreative"><a href="http://illcreative.com">illuminati</a></div>
</div>

app/views/shared/_right_info.html.erb
<div class="sidebar clearfix">
	<div class="search clearfix">
  		<%= form_tag('/search', :class =>'form-search') %>
    		<input type="text" name="address" id="address" autofocus class="input-medium search-query" placeholder="Search Locations...">
		  	<button type="submit" class="btn">Search</button>
		</form>
	</div>
	<div class="wrap clearfix">
		<section>
			<h2>Help your fellow New Yorkers!</h2>
			<p>This site only displays information provided by the landlords, superintendents, and residents of New York City. If you have information about a building in NYC please update the website as accurately as possible.</p>
		</section>
		<section>
			<h3>Resources</h3>
			<ul class="resources">
				<li><a href="http://www.nyc.gov" target="_blank">NYC.gov</a></li>
				<li><a href="https://twitter.com/notifynyc" target="_blank">Notify NYC</a></li>
				<li><a href="http://project.wnyc.org/transit-tracker/embed.html" target="_blank">Transit Tracker</a></li>
				<li><a href="http://google.org/crisismap/2012-sandy" target="_blank">Google Crisis Map</a></li>
				<li><a href="http://coned.com" target="_blank">Con Edison</a></li>
				<li><a href="http://www.disasterassistance.gov/" target="_blank">Disaster Assistance</a></li>
			</ul>
		</section>
		<section class="about">
			<h3>About</h3>
			<p>Get Home Safe NYC is available for residents of New York City to update and discover the status of critical resources at their homes and apartments in the wake of Hurricane Sandy. The website allows landlords and fellow residents to list their address and mark whether the residence has power, electricity, running water, working elevators (if applicable) or has experienced flooding. Most importantly, it will indicate if it is safe to return to the residence.</p>
		</section>
		<section class="disclaimer">	
			<p><span class="prompt">Disclaimer: </span>The information on this website is for public informational purposes only and is not reviewed by the site owners. Get Home Safe NYC and its parents assume no responsibility to parties receiving and using the information. By using this website you acknowledge this.</p>
		</section>
	</div>
</div>

app/views/welcome/index.html.erb
<div class="boroughs">
  <h2>Search your building status</h2>
  <ul>
    <li class="manhattan"><a id="manhattan" href="search?borough=manhattan">Manhattan »</a></li>
    <li class="bronx"><a href="search?borough=manhattan">Bronx »</a></li>
    <li class="queens"><a href="search?borough=manhattan">Queens »</a></li>
    <li class="brooklyn"><a href="search?borough=manhattan">Brooklyn »</a></li>
    <li class="staten_island"><a href="search?borough=manhattan">Staten Island »</a></li>
  </ul>
</div>

app/views/welcome/press.html.erb
<div class="press">
	<h2>New Web Service Helps NYers Return Home</h2>
	<p>A free web service is now available for residents of New York City to update and discover the status of critical resources at their homes and apartments in the wake of Hurricane Sandy: Get Home Safe NYC (<a href="http://gethomesafenyc.com">www.gethomesafenyc.com</a>)</p>
	<p>The website allows landlords and fellow residents to list their address and mark whether the residence has power, heat, running water, working elevators (if applicable) or has experienced flooding. Most importantly, they can indicate if it is safe to return to the residence. The information on the website is "crowdsourced," meaning the website users are providing the information listed. This offers the ability to provide the most accurate and up-to-date information by the people who live and work at the addresses listed.</p>
	<p>Get Home Safe NYC asks landlords, building/property managers, and residents to visit the site and add information for the buildings they are familiar with. The site is completely free to use, and is accessible on both desktop computers and mobile devices.</p>
	<p>Get Home Safe NYC was built in the wake of Hurricane Sandy by <a href="http://illcreative.com">Illuminati Creative</a> (www.illcreative.com), a boutique digital agency specializing in interactive design and development for web, iOS and Android applications.</p>
	<p>For more information, contact:</p>
	<p>Paul Molluzzo<br />
	Director, Client Engagement<br/>
	Illuminati Creative, LLC<br />
	<a href="mailto:paul@illcreative.com?subject=Get%20Home%20Safe%20NYC">paul@illcreative.com</a><br />
	212-380-7628 ext. 2</p>
	<p class="pounds">###</p>
</div>

app/views/welcome/terms.html.erb
<div class="terms">
	<h2>Terms and Conditions</h2>
	<p>GetHomeSafeNYC.com ("GHS" or the "Site") is maintained by Illuminati Creative, LLC ("Illuminati") for your personal use. Please feel free to browse and add information to the Site. Your access to and use of the Site is also subject to the following terms and conditions (hereafter collectively called "Terms and Conditions") and all applicable laws. By accessing and browsing the Site, you accept and agree to be bound by the Terms and Conditions. Our aim has been to make the Terms and Conditions unambiguous and fair to all parties, but if further explanation is required, please go to <a href="http://illcreative.com" target="_blank" title="Illuminati Creative">www.illcreative.com</a> and proceed to the contact information page for further details on how to contact us.</p>
	<ol>
		<li>All information contained on, distributed through, or linked, downloaded or accessed from any of the services contained on this website is for informational purposes only. The information contained on this site has been obtained from public sources without review or verification by GHS, Illuminati or any of its officers, directors or members, and all of those parties make no representations with respect to the accuracy of the information. All information is provided "as is" without any warranty of any kind. GHS and Illuminati disclaim all express, implied and statutory warranties of any kind to any party including warranties as to the accuracy, completeness, merchantability or fitness for any particular purpose. Because of the possibility of human and mechanical error as well as other factors, GHS and Illuminati shall under no circumstances be liable for any errors or omissions.</li>
		<li>You may use materials displayed on the Site for non-commercial, personal use. Except where otherwise stated, GHS and Illuminati are the copyright holders for all Content, and these terms and conditions in no way imply any transfer of that copyright to the User. Users may not modify or adapt in any way any of the Content protected by these copyrights. Copyright notices must not be modified or removed from any Content obtained under the terms of this license.</li>
		<li>Nothing shall be construed to license any copyright, patent, trademark or other intellectual property rights existing in the Site. GHS and Illuminati make no warranties or representations as to accuracy of the materials displayed on the Site. Systematic downloading and/or archiving, including the copying of entire volume numbers is prohibited. Individual and/or collective information may not be used for the purposes of monetary reward by means of sale, resale, loan, transfer, hire or other form of exploitation of the Content, and may not be systematically supplied or distributed onward from the site or premises of the User.</li>
		<li>YOUR USE OF AND BROWSING IN THE SITE AND ALL RESULTS DERIVED FROM THE USE AND BROWSING ARE AT YOUR RISK. NEITHER GHS OR ILLUMINATI NOR ANY OTHER PARTY INVOLVED IN CREATING, PRODUCING OR DELIVERING THE SITE IS LIABLE FOR ANY DAMAGES ARISING OUT OF YOUR ACCESS TO, OR USE OF, THE SITE. EVERYTHING ON THE SITE IS PROVIDED TO YOU "AS IS" WITHOUT WARRANTY OF ANY KIND, EITHER EXPRESSED OR IMPLIED, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE, OR NON-INFRINGEMENT. GHS and Illuminati shall not be liable for any damages to, or viruses that may infect, your computer equipment on account of your access to, use of, or browsing in the Site or your using of any materials, data, text, images, video or audio displayed on the Site. GHS and Illuminati shall under no circumstances be liable to any party for any lost profit or lost opportunity, indirect, special, consequential, incidental, or punitive damages whatsoever. Although GHS and Illuminati is unable to ensure that the information, data and other material made available online is error-free and up-to-date, and accepts no responsibility for corruption to the information, data and other material thereafter, including but not limited to any defects caused by the transmission or processing of the information, data and other material. The information made available online has been obtained from or is based upon sources public sources without review or verification and is not guaranteed as to accuracy or completeness. The information is supplied without obligation and on the understanding that any person who acts upon it or otherwise changes his/her position in reliance thereon does so entirely at his/her own risk.</li>
		<li>GHS and Illuminati shall use all reasonable means to provide uninterrupted electronic availability of the Site, but if access is suspended or interrupted or a fault or defect occurs which prevents access to the server, GHS and Illuminati shall accept no liability. The User is responsible for all charges associated with accessing the content, including any computer equipment, telephone or Internet connections and access software. GHS and Illuminati reserve the right to refuse access to any individual, network or User at any time. Although GHS and Illuminati products are developed in view of maximum compatibility and user-friendliness, GHS and Illuminati cannot guarantee any of these products to work on or with any particular computer system.</li>
		<li>GHS and Illuminati have no obligation for monitoring any ideas, concepts, suggestions or comments (hereafter collectively called "Ideas") you transmit to GHS and Illuminati by electronic mail or otherwise. GHS and Illuminati understand that you abandon all rights regarding the Ideas at the time when you transmit the Ideas to GHS and Illuminati, and GHS and Illuminati has no obligations to keep the Ideas confidential. GHS and Illuminati has no responsibility for any problems or issues resulted from the Ideas. GHS and Illuminati have the right to delete such Ideas from servers without notice.</li>
		<li>You are prohibited from sending any unlawful, threatening, libel, defamatory, obscene, scandalous, inflammatory, pornographic or profane electronic mails etc. that could constitute or encourage conduct that would be considered a criminal offense, give rise to civil liability or otherwise violate any law. GHS and Illuminati have a right to delete such information from servers without notice.</li>
		<li>The trademarks, logos and service marks (hereafter collectively called "Trademarks") displayed on the Site are registered and unregistered Trademarks of GHS, Illuminati and others.</li>
		<li>GHS and Illuminati are not responsible for the content of any other sites linked to the Site.</li>
		<li>GHS and Illuminati may at any time revise these Terms and Conditions by updating. You are bound by any such revisions and should therefore periodically visit this page to review the then current Terms and Conditions to which you are bound.</li>
	</ol>
</div>